spring:
  application:
    name: unit-converter-service
  profiles:
    active: local



conversion:
  facts:
    - from: meter
      to: feet
      factor: 3.28
    - from: feet
      to: inch
      factor: 12
    - from: inch
      to: centimeter
      factor: 2.54
    - from: hour
      to: minute
      factor: 60
    - from: minute
      to: second
      factor: 60


management:
  endpoints:
    web:
      exposure:
        include:
        - prometheus
---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: ""

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8080